version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_university
    restart: always
    environment:
      MYSQL_DATABASE: university_system
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:

networks:
  backend:
